// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3o2AQaBxS2Jy8PHXG033mZPM2euSf2po',
    appId: '1:132997509899:web:2e9dfa2d1113a1ac69280e',
    messagingSenderId: '132997509899',
    projectId: 'fixright-project',
    authDomain: 'fixright-project.firebaseapp.com',
    storageBucket: 'fixright-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtvJ6rbFfg0066BpGgbbvZTYR5SiQOcc',
    appId: '1:132997509899:android:5986ff6f42fdec7369280e',
    messagingSenderId: '132997509899',
    projectId: 'fixright-project',
    storageBucket: 'fixright-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYMk3vuCvgos8zJTcKzYJzzxTsfXzwAuA',
    appId: '1:132997509899:ios:a1c30a465650954b69280e',
    messagingSenderId: '132997509899',
    projectId: 'fixright-project',
    storageBucket: 'fixright-project.firebasestorage.app',
    iosBundleId: 'com.example.fixright',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYMk3vuCvgos8zJTcKzYJzzxTsfXzwAuA',
    appId: '1:132997509899:ios:a1c30a465650954b69280e',
    messagingSenderId: '132997509899',
    projectId: 'fixright-project',
    storageBucket: 'fixright-project.firebasestorage.app',
    iosBundleId: 'com.example.fixright',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3o2AQaBxS2Jy8PHXG033mZPM2euSf2po',
    appId: '1:132997509899:web:55a56b04176e74f369280e',
    messagingSenderId: '132997509899',
    projectId: 'fixright-project',
    authDomain: 'fixright-project.firebaseapp.com',
    storageBucket: 'fixright-project.firebasestorage.app',
  );
}
