import 'package:flutter/material.dart';
import './src/pages/ClientMainScreen.dart';
import './src/components/LoginPage.dart';
// // // Import your pages
// // // The HomePage we built
// import 'src/pages/login_page.dart'; // Uncomment when you create LoginPage

// // void main() {
// //   runApp(const FixRightApp());
// // }

// // class FixRightApp extends StatelessWidget {
// //   const FixRightApp({super.key});

// //   @override
// //   Widget build(BuildContext context) {
// //     return MaterialApp(
// //       title: 'FixRight',
// //       debugShowCheckedModeBanner: false,
// //       theme: ThemeData(primarySwatch: Colors.indigo, useMaterial3: true),
// //       // Start the app directly on HomePage
// //       initialRoute: '/',
// //       routes: {
// //         '/home': (context) => const ClientMainScreen(),
// //         '/': (context) => const LoginPage(), // temp route
// //       },
// //     );
// //   }
// // }

// import 'package:firebase_core/firebase_core.dart';
// import 'package:flutter/material.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure`
// import 'src/pages/ClientMainScreen.dart';
// import 'src/components/LoginPage.dart';
// import 'src/components/SIgnupPage.dart'; // adjust path if you named differently
// import 'package:flutter_dotenv/flutter_dotenv.dart';


// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
//    await dotenv.load(fileName: ".env");
//   runApp(const FixRightApp());
// }

// class FixRightApp extends StatelessWidget {
//   const FixRightApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     // main blue used in your mock
//     const primaryBlue = Color(0xFF2B7CD3);

//     final theme = ThemeData(
//       primaryColor: primaryBlue,
//       colorScheme: ColorScheme.fromSeed(seedColor: primaryBlue),
//       scaffoldBackgroundColor: const Color(0xFFE9F2FB), // subtle background
//       useMaterial3: true,
//       appBarTheme: const AppBarTheme(
//         backgroundColor: Colors.white,
//         foregroundColor: Colors.black87,
//         elevation: 0,
//         centerTitle: true,
//       ),
//       elevatedButtonTheme: ElevatedButtonThemeData(
//         style: ElevatedButton.styleFrom(
//           backgroundColor: primaryBlue,
//           foregroundColor: Colors.white,
//           minimumSize: const Size.fromHeight(48),
//           shape: RoundedRectangleBorder(
//             borderRadius: BorderRadius.circular(10),
//           ),
//         ),
//       ),
//     );

//     return MaterialApp(
//       title: 'FixRight',
//       debugShowCheckedModeBanner: false,
//       theme: theme,
//       initialRoute: '/',
//       routes: {
//         '/': (context) => const LoginPage(),
//         '/home': (context) => const ClientMainScreen(),
//         '/signup':(context) => const SignupScreen(),
        
//       },
//     );
//   }
// }



// // lib/main.dart (partial update)

// // ... (existing imports)
// import 'src/pages/ClientMainScreen.dart';
// import 'src/pages/app_mode_switcher.dart'; // NEW IMPORT

// import 'src/components/LoginPage.dart';
// import 'src/components/SIgnupPage.dart';
// void main() async {
// // ... (Firebase and dotenv initialization) ...
//   runApp( FixRightApp());
// }

// class FixRightApp extends StatelessWidget {
// // ... (existing theme code) ...
//   @override
//   Widget build(BuildContext context) {
//     // ... (theme definition) ...

//     return MaterialApp(
//       title: 'FixRight',
//       debugShowCheckedModeBanner: false,
      
//       initialRoute: '/',
//       routes: {
//         '/': (context) => const LoginPage(),
//         // CHANGE: Authenticated users now go to the AppModeSwitcher
//         '/home': (context) => const AppModeSwitcher(), 
//         '/signup': (context) => const SignupScreen(),
//       },
//     );
//   }
// }



// lib/main.dart

import 'package:firebase_core/firebase_core.dart'; // Ensure this is imported
import 'package:flutter/material.dart';
import 'firebase_options.dart'; // Ensure this is imported and correctly generated
import 'src/pages/ClientMainScreen.dart';
import 'src/components/LoginPage.dart';
import 'src/components/SignupPage.dart'; // Corrected class name
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'src/pages/app_mode_switcher.dart'; // Ensure this is imported (for '/home')


void main() async {
  // 1. Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized(); 

  // 2. Initialize Firebase BEFORE running the app
  // This step creates the default Firebase App instance
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  ); 
  
  // 3. Load other async resources (like environment variables)
  await dotenv.load(fileName: ".env");

  runApp( FixRightApp());
}

class FixRightApp extends StatelessWidget {
  const FixRightApp({super.key});

// ... (rest of the class remains the same)
// ... (theme definition) ...
  @override
  Widget build(BuildContext context) {
    // ... (theme definition) ...

    return MaterialApp(
      title: 'FixRight',
      debugShowCheckedModeBanner: false,
    
      initialRoute: '/',
      routes: {
        '/': (context) => const LoginPage(),
        '/home': (context) => const AppModeSwitcher(),
        '/signup': (context) => const SignupScreen(), // Assuming SignupScreen is the class name
      },
    );
  }
}