// import 'package:flutter/material.dart';
// import './src/pages/ClientMainScreen.dart';
// import './src/components/LoginPage.dart';
// // Import your pages
// // The HomePage we built
// // import 'src/pages/login_page.dart'; // Uncomment when you create LoginPage

// void main() {
//   runApp(const FixRightApp());
// }

// class FixRightApp extends StatelessWidget {
//   const FixRightApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'FixRight',
//       debugShowCheckedModeBanner: false,
//       theme: ThemeData(primarySwatch: Colors.indigo, useMaterial3: true),
//       // Start the app directly on HomePage
//       initialRoute: '/',
//       routes: {
//         '/home': (context) => const ClientMainScreen(),
//         '/': (context) => const LoginPage(), // temp route
//       },
//     );
//   }
// }

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'src/pages/ClientMainScreen.dart';
import 'src/components/LoginPage.dart';
import 'src/components/SIgnupPage.dart'; // adjust path if you named differently
import 'package:flutter_dotenv/flutter_dotenv.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
   await dotenv.load(fileName: ".env");
  runApp(const FixRightApp());
}

class FixRightApp extends StatelessWidget {
  const FixRightApp({super.key});

  @override
  Widget build(BuildContext context) {
    // main blue used in your mock
    const primaryBlue = Color(0xFF2B7CD3);

    final theme = ThemeData(
      primaryColor: primaryBlue,
      colorScheme: ColorScheme.fromSeed(seedColor: primaryBlue),
      scaffoldBackgroundColor: const Color(0xFFE9F2FB), // subtle background
      useMaterial3: true,
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.white,
        foregroundColor: Colors.black87,
        elevation: 0,
        centerTitle: true,
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: primaryBlue,
          foregroundColor: Colors.white,
          minimumSize: const Size.fromHeight(48),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
        ),
      ),
    );

    return MaterialApp(
      title: 'FixRight',
      debugShowCheckedModeBanner: false,
      theme: theme,
      initialRoute: '/',
      routes: {
        '/': (context) => const LoginPage(),
        '/home': (context) => const ClientMainScreen(),
        '/signup':(context) => const SignupScreen(),
        
      },
    );
  }
}
